# Generated by Django 4.2 on 2023-04-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('population', models.IntegerField()),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weather_condition', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('geo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='brewingweather_app.geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='geolocation',
            name='search_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_locations', to='brewingweather_app.searchhistory'),
        ),
    ]
